### PR TITLE
Move CI to GitHub Actions

### PR DESCRIPTION
**Pull request by hugovk**
Travis CI has a new pricing model which places limits on open source.

* https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing
* https://www.jeffgeerling.com/blog/2020/travis-cis-new-pricing-plan-threw-wrench-my-open-source-works

Many projects are moving to GitHub Actions instead, and we're moving the python-pillow repos over: https://github.com/python-pillow/Pillow/issues/5028.

This PR removes the Travis CI testing and does the same on GitHub Actions.

Once difference: GHA doesn't have `allow_failures` like Travis does, and the `3.10-dev` (which is the closest to `nightly` on Travis) is failing because Wheel doesn't yet support 3.10: https://github.com/pypa/wheel/issues/354. So that's commented out for now.

Example build:

* https://github.com/hugovk/pillow-perf/actions/runs/365836504

### CODE REVIEW

**Comment by nulano** [comment]
> Once difference: GHA doesn't have `allow_failures` like Travis does, and the `3.10-dev` (which is the closest to `nightly` on Travis) is failing because Wheel doesn't yet support 3.10: [pypa/wheel#354](https://github.com/pypa/wheel/issues/354). So that's commented out for now.

There is https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idcontinue-on-error, but it's not entirely clear to me what it does from the documentation and I haven't tried it myself.

**Comment by hugovk** [comment]
> Currently, using ‘continue-on-error:’ in a step flags the step with a green check and allows the job to continue.  The only way to see if the step failed is to look at the step’s log.

https://github.community/t/continue-on-error-allow-failure-ui-indication/16773

Also: https://github.com/actions/toolkit/issues/399

**Comment by homm** [comment]
Do we need to enable Actions somehow for the repo first to see this config *in action*? )

**Comment by hugovk** [comment]
It should be enabled on merge.

Or you could try pushing my fork's branch to a branch in this repo, that might do it.

You can see a test run https://github.com/hugovk/pillow-perf/actions/runs/365836504

If you prefer, we could keep `.travis.yml` in this PR, merge, and remove it in a followup PR.

**Pull request merged**
