### PR TITLE
Run testsuites on Travis CI

### PR DESCRIPTION
**Pull request by hugovk**
Are you interested on running these on Travis CI?

It at least shows that the commands run without erroring on each Python version, and also gives a log of performance at different times.

For example: https://travis-ci.org/hugovk/pillow-perf/builds/170152407

(Python 2.6 is listed under `allow_failures` so it doesn't fail the whole build, as it doesn't support some `format` calls used.)

Travis CI will need syncing and enabling here by someone with admin rights (I don't have them): https://travis-ci.org/profile/python-pillow

 * Also removes some unused imports found by `pyflakes`.

### CODE REVIEW

**Comment by homm** [comment]
> It at least shows that the commands run without erroring on each Python version

This can be useful.

> and also gives a log of performance at different times.

I'm not sure about this. First, we don't specify Pillow version, it always the last.
Second, Travis is not right environment for performance tests. For exampale, results should be near the same for this tests:

```bash
$ ./run.py blur
### blur
    1px                   0.22107 s    18.53 Mpx/s
    10px                  0.32453 s    12.62 Mpx/s
    30px                  0.21971 s    18.64 Mpx/s
```

I think that just syntax check should be enought. Something like this:

```bash
$ ./run.py convert scale blur composition wand_scale -s 512x512 -n 1
```

**Comment by hugovk** [comment]
OK, updated.

**Comment by homm** [comment]
@wiredfool @aclark4life 

I need somebody to add the repo on Travis:

https://travis-ci.org/profile/python-pillow

**Comment by aclark4life** [comment]
@homm Done

screenshot 2016-10-30 07 41 38

**Comment by hugovk** [comment]
Thanks!

I've re-pushed the last commit to trigger a build.

**Comment by homm** [comment]
@hugovk To be honest, I'd like do not support python 2.6 at all. I never saw it in a wild and it useless with `allow_failures` flag.

**Comment by hugovk** [comment]
@homm Python 2.6 removed.

**Pull request merged**
